services:
  nginx:
    image: nginx:1.25
    container_name: nginx-1.25 
    restart: always
    volumes:
      - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf/conf.d:/etc/nginx/conf.d"
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/log:/var/log/nginx"
    environment:                        
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    ports:                              
      - "80:80"
      - "443:443"
    networks:
      - nginx-net

networks:
  nginx-net:
    driver: bridge